### ISSUE TITLE
Top navbar is invisible on course home page sometimes

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#110]
![screenshot from 2013-12-03 11 34 42](https://f.cloud.github.com/assets/719730/1665568/d480b972-5c38-11e3-881d-8bab3d3bdc5c.png)

**Comment by zdwolfe** [comment]
```
ogin angular.js:8296
TypeError: Cannot set property 'name' of undefined
    at Scope.$scope.resetNavBar (http://localhost/scripts/controllers/main.js:30:26)
    at http://localhost/bower_components/angular/angular.js:9067:21
    at http://localhost/bower_components/angular/angular.js:16515:13
    at Scope.$eval (http://localhost/bower_components/angular/angular.js:10699:28)
    at Scope.$apply (http://localhost/bower_components/angular/angular.js:10796:23)
    at HTMLAnchorElement.<anonymous> (http://localhost/bower_components/angular/angular.js:16514:17)
    at HTMLAnchorElement.x.event.dispatch (http://localhost/bower_components/jquery/jquery.min.js:5:10006)
    at HTMLAnchorElement.y.handle (http://localhost/bower_components/jquery/jquery.min.js:5:6789) angular.js:8296

```
