### ISSUE TITLE
HomepageTimeline.js TypeError

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#130]
Getting error:

```
TypeError: Cannot read property 'length' of undefined
    at Scope.$scope.loadMorePosts (http://localhost/scripts/controllers/HomepageTimeline.js:28:73)
    at http://localhost/bower_components/angular/angular.js:9067:21
    at Scope.$eval (http://localhost/bower_components/angular/angular.js:10699:28)
    at Scope.$apply (http://localhost/bower_components/angular/angular.js:10796:23)
    at handler (http://localhost/bower_components/ngInfiniteScroll/ng-infinite-scroll.js:39:28)
    at http://localhost/bower_components/ngInfiniteScroll/ng-infinite-scroll.js:55:20
    at http://localhost/bower_components/angular/angular.js:12286:28
    at completeOutstandingRequest (http://localhost/bower_components/angular/angular.js:3740:10)
    at http://localhost/bower_components/angular/angular.js:4041:7 


```

![screenshot from 2013-12-07 18 59 06](https://f.cloud.github.com/assets/719730/1699419/95a5ce66-5f9b-11e3-8d82-59d9d586bec5.png)

**Comment by zdwolfe** [comment]
@slb5427  Getting the same thing in `Timeline.js`

```
TypeError: Cannot read property 'length' of undefined
    at Scope.$scope.loadMorePosts (http://localhost/scripts/controllers/Timeline.js:37:73)
    at http://localhost/bower_components/angular/angular.js:9067:21
    at Scope.$eval (http://localhost/bower_components/angular/angular.js:10699:28)
    at Scope.$apply (http://localhost/bower_components/angular/angular.js:10796:23)
    at handler (http://localhost/bower_components/ngInfiniteScroll/ng-infinite-scroll.js:39:28)
    at http://localhost/bower_components/ngInfiniteScroll/ng-infinite-scroll.js:55:20
    at http://localhost/bower_components/angular/angular.js:12286:28
    at completeOutstandingRequest (http://localhost/bower_components/angular/angular.js:3740:10)
    at http://localhost/bower_components/angular/angular.js:4041:7 angular.js:8296
```
